#!/usr/bin/env python3

import os
import datetime
import fileinput

file_name = "robots.txt"

#### build hash
build = os.popen('git rev-parse --short HEAD').read()


#### title (figlet -m 1 -f slant "ai.robots.blk")
print(rf"""
               __          __        __ 
   _________  / /_  ____  / /_ _  __/ /_
  / ___/ __ \/ __ \/ __ \/ __/| |/_/ __/
 / /  / /_/ / /_/ / /_/ / /_ _>  </ /_  
/_/   \____/_.___/\____/\__//_/|_|\__/  

 ------------------------- build {build}""")

#### questions
sites_dom = input("[?] Enter your site's domain (mysite.com): ")
searc_yrn = input("[?] Allow AI search bots to index your site? (Y/N): ") 
train_yrn = input("[?] Allow AI training bots to access your site? (y/n): ") 
print('\n' + '[*] Results: ')
print('     - Domain: ' + sites_dom)
print('     - Search: ' + searc_yrn)
print('     - Train:  ' + train_yrn)

#### create empty file
print('[-] Creating: ' + file_name)
with open(file_name, 'w') as file:
    file.write('#### robots.txt \n\n')

#### user-agent rules
print('[-] Writing: user-agent rules')
with open(file_name, 'a') as fout, fileinput.input('src/ua-block-search-block-train.txt') as fin:
    for line in fin:
        fout.write(line)
    fout.write('\n')

#### sitemap
print('[-] Writing: sitemap section')
with open(file_name, 'a') as fout, fileinput.input('src/sitemap.txt') as fin:
    for line in fin:
        fout.write(line)
with open(file_name, "a") as file:
    file.write("Sitemap: https://" + sites_dom + "/sitemap.xml\n\n")

#### disclaimer 
print('[-] Writing: disclaimer section')
with open(file_name, 'a') as fout, fileinput.input('src/disclaimer.txt') as fin:
    for line in fin:
        fout.write(line)

#### about
print('[-] Writing: about section')
with open(file_name) as inputfile, open(file_name, 'a') as outputfile:
        outputfile.write('\n')
with open(file_name, 'a') as fout, fileinput.input('src/about.txt') as fin:
    for line in fin:
        fout.write(line)

#### timestamp
print('[-] Writing: timestamp to ' + file_name)
with open(file_name, 'a') as file:
    file.write(f"# * File {file_name} created on {datetime.datetime.now()} \n")

#### summary
if os.path.exists(file_name):
    print('[*] Created: ' + file_name + ' see file for details and usage')
                                                               
